import { z } from "zod";

/** Validated body for POST /v1/sessions/:sessionId/messages. */
export const messageRequestSchema = z.object({
  message: z.string().min(1).max(20000),
  idempotencyKey: z.string().max(200).optional(),
  /** Capabilities pre-approved by the authenticated caller. */
  approvals: z.array(z.string().max(128)).max(32).optional(),
  /** Test-only scripted model decisions (ignored unless explicitly enabled). */
  modelScript: z.array(z.unknown()).max(64).optional(),
});

export type MessageRequest = z.infer<typeof messageRequestSchema>;

/** Session ids are constrained to a safe character set and length. */
export const sessionIdSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Za-z0-9._:-]+$/, "invalid session id");

/** Run ids are UUIDs generated by the runtime. */
export const runIdSchema = z.string().min(1).max(128).regex(/^[A-Za-z0-9-]+$/);
